// Teacher-reviewable introductory CE2134 practice. Tolerances are absolute,
// in the displayed answer unit. Every numerical question states its assumptions.
export const questions = [
  {
    id: 'pressure-01', topic: 'pressure', title: 'At an open free surface',
    kind: 'choice', difficulty: 'Foundation',
    prompt: 'What is the gauge pressure at the free surface of a liquid open to the atmosphere?',
    choices: ['0 kPa', '101.3 kPa for every location', '9.80 kPa', 'It depends on the liquid density'], answerIndex: 0,
    hint: 'Gauge pressure uses the surrounding atmospheric pressure as its reference.',
    solution: ['Gauge pressure is absolute pressure minus local atmospheric pressure.', 'At the open surface these pressures are equal, so the gauge pressure is 0 kPa.'],
    takeaway: 'An open free surface has zero gauge pressure, even when atmospheric pressure changes.',
    tags: ['pressure-reference', 'free-surface'],
  },
  {
    id: 'pressure-02', topic: 'pressure', title: 'Pressure at depth',
    kind: 'numeric', difficulty: 'Foundation',
    prompt: 'Find the gauge pressure 2.50 m below the free surface of still water in an open tank.',
    given: 'Water density ρ = 1000 kg/m³; g = 9.80 m/s².', answer: 24.5, unit: 'kPa', tolerance: 0.05,
    hint: 'Use the vertical water depth in p = ρgh, then convert Pa to kPa.',
    solution: ['p = 1000 × 9.80 × 2.50 = 24,500 Pa.', 'Divide by 1000: p = 24.50 kPa gauge.'],
    takeaway: 'Hydrostatic gauge pressure increases linearly with vertical depth.',
    tags: ['hydrostatic-pressure', 'units'],
  },
  {
    id: 'pressure-03', topic: 'pressure', title: 'From gauge to absolute',
    kind: 'numeric', difficulty: 'Apply',
    prompt: 'Find the absolute pressure 2.00 m below the free surface of an open water tank.',
    given: 'ρ = 1000 kg/m³; g = 9.80 m/s²; local atmospheric pressure = 101.3 kPa.',
    answer: 120.9, unit: 'kPa absolute', tolerance: 0.05,
    hint: 'Calculate the gauge pressure first, then add atmospheric pressure.',
    solution: ['Gauge pressure = 1000 × 9.80 × 2.00 / 1000 = 19.60 kPa.', 'Absolute pressure = 101.3 + 19.60 = 120.90 kPa.'],
    takeaway: 'Always identify the pressure reference before substituting a value.',
    tags: ['pressure-reference', 'hydrostatic-pressure'],
  },
  {
    id: 'pressure-04', topic: 'pressure', title: 'Connected water at rest',
    kind: 'choice', difficulty: 'Apply',
    prompt: 'Two points lie at the same elevation in the same connected body of homogeneous water at rest. How do their pressures compare?',
    given: 'Gravity is uniform; the water is at rest throughout the connecting passage.',
    choices: ['The point nearest a wall has higher pressure', 'Their pressures are equal', 'The wider part of the container has higher pressure', 'Pressure depends only on the total water volume'], answerIndex: 1,
    hint: 'In a stationary homogeneous liquid, a horizontal pressure difference would drive motion.',
    solution: ['The hydrostatic relation is dp/dz = −ρg.', 'For equal elevations in the connected liquid, the pressure difference is zero. Container shape does not alter this result.'],
    takeaway: 'In a connected homogeneous liquid at rest, equal elevation means equal pressure.',
    tags: ['hydrostatic-equilibrium', 'connected-fluid'],
  },
  {
    id: 'pressure-05', topic: 'pressure', title: 'Two fluid layers',
    kind: 'numeric', difficulty: 'Apply',
    prompt: 'An open tank contains 0.50 m of oil above 1.20 m of water. Find the gauge pressure at the tank bottom.',
    given: 'Oil density = 800 kg/m³; water density = 1000 kg/m³; g = 9.80 m/s². Both layers are at rest.',
    answer: 15.68, unit: 'kPa', tolerance: 0.03,
    hint: 'Add each layer’s ρgh contribution; use each density only with its own depth.',
    solution: ['Oil contribution = 800 × 9.80 × 0.50 = 3920 Pa.', 'Water contribution = 1000 × 9.80 × 1.20 = 11,760 Pa.', 'Bottom gauge pressure = (3920 + 11,760) / 1000 = 15.68 kPa.'],
    takeaway: 'Each fluid layer adds a separate pressure contribution.',
    tags: ['layered-fluids', 'hydrostatic-pressure'],
  },
  {
    id: 'pressure-06', topic: 'pressure', title: 'Reading a layered-fluid graph',
    kind: 'choice', difficulty: 'Connect',
    prompt: 'A graph plots gauge pressure against downward depth through oil into denser water. What happens at the horizontal interface?',
    given: 'Both fluids are at rest. Neglect surface-tension effects.',
    choices: ['Pressure jumps upward but the slope stays unchanged', 'Pressure falls to zero at the interface', 'Pressure stays continuous and its slope becomes steeper', 'Pressure stays continuous and its slope becomes less steep'], answerIndex: 2,
    hint: 'Distinguish the pressure itself from the pressure gradient ρg.',
    solution: ['Pressure is continuous across the interface under the stated assumptions.', 'The downward pressure gradient is dp/dh = ρg, so entering the denser water increases the slope.'],
    takeaway: 'An interface changes the hydrostatic gradient, not the pressure continuity.',
    tags: ['layered-fluids', 'pressure-depth-graph'],
  },
  {
    id: 'forces-01', topic: 'forces', title: 'Resultant on a plane surface',
    kind: 'choice', difficulty: 'Foundation',
    prompt: 'Which expression gives the magnitude of the net hydrostatic force on a submerged plane area A?',
    given: 'Homogeneous liquid at rest, open free surface; the opposite side is at atmospheric pressure. h̄ is the vertical depth of the area centroid.',
    choices: ['F = ρgA, regardless of depth', 'F = ρg h̄ A', 'F = ρg hCP A, using the centre-of-pressure depth', 'F = ρg h̄ / A'], answerIndex: 1,
    hint: 'For a plane area, the area-average hydrostatic pressure equals the pressure at its centroid.',
    solution: ['Integrate gauge pressure over the surface: F = ∫A ρgh dA.', 'Since ∫A h dA = h̄A, the resultant magnitude is F = ρg h̄A.'],
    takeaway: 'The centroid determines force magnitude; the centre of pressure determines its location.',
    tags: ['plane-surface', 'resultant-force'],
  },
  {
    id: 'forces-02', topic: 'forces', title: 'A vertical rectangular gate',
    kind: 'numeric', difficulty: 'Foundation',
    prompt: 'A vertical rectangular gate is 2.00 m wide and 3.00 m high, with its top edge at the water free surface. Find the net hydrostatic force magnitude.',
    given: 'ρ = 1000 kg/m³; g = 9.80 m/s². Water is on one side; the other side is at atmospheric pressure.',
    answer: 88.2, unit: 'kN', tolerance: 0.1,
    hint: 'The centroid is halfway down the gate; use its vertical depth and the full gate area.',
    solution: ['Area A = 2.00 × 3.00 = 6.00 m²; centroid depth h̄ = 1.50 m.', 'F = 1000 × 9.80 × 1.50 × 6.00 = 88,200 N = 88.20 kN.'],
    takeaway: 'A triangular pressure distribution has its average pressure halfway between its end values.',
    tags: ['plane-surface', 'resultant-force'],
  },
  {
    id: 'forces-03', topic: 'forces', title: 'Locate the centre of pressure',
    kind: 'numeric', difficulty: 'Apply',
    prompt: 'A vertical rectangular gate is 1.00 m wide and 2.00 m high. Its top edge is 1.00 m below the free surface. Find the centre-of-pressure depth below the free surface.',
    given: 'Homogeneous water at rest on one side; atmospheric pressure on the other. Use hCP = h̄ + IG/(h̄A), with IG about the horizontal centroidal axis.',
    answer: 2.1666666666666665, unit: 'm', tolerance: 0.005,
    hint: 'For a rectangle, IG = bH³/12. The centroid depth is not measured from the gate’s top edge.',
    solution: ['h̄ = 1.00 + 2.00/2 = 2.00 m; A = 1.00 × 2.00 = 2.00 m².', 'IG = 1.00 × 2.00³/12 = 2/3 m⁴.', 'hCP = 2.00 + (2/3)/(2.00 × 2.00) = 2.167 m below the free surface.'],
    takeaway: 'For this gate, the centre of pressure lies below the area centroid.',
    tags: ['plane-surface', 'centre-of-pressure'],
  },
  {
    id: 'forces-04', topic: 'forces', title: 'Horizontal force on a curved gate',
    kind: 'choice', difficulty: 'Apply',
    prompt: 'How is the horizontal hydrostatic force component on a curved gate found?',
    given: 'The liquid is stationary and homogeneous; use gauge pressure relative to the atmosphere on the opposite side.',
    choices: ['Use the weight of the gate material', 'Multiply pressure at the deepest point by the curved area', 'Use the pressure force on the gate’s horizontal projection', 'Use the hydrostatic force on its vertical projection'], answerIndex: 3,
    hint: 'Resolve each pressure force into the chosen horizontal direction before integrating.',
    solution: ['The horizontal components of pressure acting on the curved surface integrate over its vertical projected area.', 'Apply the plane-surface hydrostatic force relation to that projection.'],
    takeaway: 'Vertical projection determines a curved surface’s horizontal force component.',
    tags: ['curved-surface', 'horizontal-projection'],
  },
  {
    id: 'forces-05', topic: 'forces', title: 'Weight of imaginary fluid',
    kind: 'numeric', difficulty: 'Apply',
    prompt: 'For a curved gate, the complete imaginary-water volume used to calculate the vertical component is 0.300 m³. Find the magnitude of that vertical hydrostatic force component.',
    given: 'ρ = 1000 kg/m³; g = 9.80 m/s². The imaginary-fluid construction is valid for this gate; pressure is gauge pressure.',
    answer: 2.94, unit: 'kN', tolerance: 0.01,
    hint: 'The vertical component is a fluid weight. Use volume, not area.',
    solution: ['FV = ρgV = 1000 × 9.80 × 0.300 = 2940 N.', 'The magnitude is 2.940 kN. Its direction must be determined separately from the gate geometry.'],
    takeaway: 'A curved gate’s vertical component comes from the appropriate imaginary-fluid weight.',
    tags: ['curved-surface', 'imaginary-fluid-volume'],
  },
  {
    id: 'forces-06', topic: 'forces', title: 'Reverse the loaded side',
    kind: 'choice', difficulty: 'Connect',
    prompt: 'The same hydrostatic pressure distribution is applied to the opposite side of a thin plane gate. What happens to the resultant?',
    given: 'The geometry and pressure at each corresponding point are unchanged; only the loaded side is reversed.',
    choices: ['Its direction reverses while its magnitude and line of action stay the same', 'Its magnitude doubles', 'Its line of action moves to the centroid', 'It becomes parallel to the gate'], answerIndex: 0,
    hint: 'Pressure acts normal to a surface. Consider the change in that normal direction.',
    solution: ['Every elemental pressure force reverses direction while keeping its magnitude.', 'The integrated resultant therefore reverses along the same line of action.'],
    takeaway: 'Loading direction and force magnitude are separate parts of a hydrostatic calculation.',
    tags: ['force-direction', 'plane-surface'],
  },
  {
    id: 'flowlines-01', topic: 'flowlines', title: 'An instantaneous flow picture',
    kind: 'choice', difficulty: 'Foundation',
    prompt: 'Which description defines a streamline?',
    choices: ['The past trajectory of one identified fluid particle', 'A curve tangent to the local velocity vectors at one instant', 'All particles that previously passed a fixed release point', 'A line that always has constant pressure'], answerIndex: 1,
    hint: 'A streamline is constructed from a snapshot of the velocity field.',
    solution: ['At a chosen instant, the streamline tangent points in the local velocity direction.', 'Its construction does not require following a particle through time.'],
    takeaway: 'Streamlines describe instantaneous velocity directions.',
    tags: ['streamlines', 'velocity-field'],
  },
  {
    id: 'flowlines-02', topic: 'flowlines', title: 'Follow one particle',
    kind: 'choice', difficulty: 'Foundation',
    prompt: 'You track one identifiable particle as it moves through a flow and draw its trajectory. Which flow line have you measured?',
    choices: ['A streamline at the final instant', 'A streakline', 'A pathline', 'A line of constant speed'], answerIndex: 2,
    hint: 'The measurement follows the history of a single particle.',
    solution: ['A pathline records the successive positions of one particle.', 'In an unsteady flow it need not match an instantaneous streamline.'],
    takeaway: 'A pathline is one particle’s history.',
    tags: ['pathlines', 'particle-tracking'],
  },
  {
    id: 'flowlines-03', topic: 'flowlines', title: 'Continuous dye release',
    kind: 'choice', difficulty: 'Apply',
    prompt: 'Dye is released continuously from one fixed point. A photograph shows the marked fluid at one instant. What does the visible curve represent?',
    given: 'Treat the dye as a passive tracer and neglect diffusion.',
    choices: ['A pathline of one particle', 'A pressure contour', 'A streamline in every possible unsteady flow', 'A streakline'], answerIndex: 3,
    hint: 'The photograph contains many particles released at different times from the same location.',
    solution: ['Every marked particle has previously passed through the fixed dye source.', 'The locus of those particles at the observation time is a streakline.'],
    takeaway: 'A streakline collects particles with a shared passage point.',
    tags: ['streaklines', 'flow-visualisation'],
  },
  {
    id: 'flowlines-04', topic: 'flowlines', title: 'When flow lines coincide',
    kind: 'choice', difficulty: 'Apply',
    prompt: 'Under which condition do streamline, pathline, and streakline curves through the same flow path coincide?',
    choices: ['The velocity field is steady in the chosen reference frame', 'The fluid density is constant, even if the flow is unsteady', 'The pressure is atmospheric everywhere', 'The flow speed is high'], answerIndex: 0,
    hint: 'Consider whether the velocity direction at each fixed location changes with time.',
    solution: ['In steady flow, the velocity field is independent of time.', 'Particles passing a point at different times follow the same geometric route, so the three descriptions coincide.'],
    takeaway: 'Steadiness links instantaneous flow geometry to particle histories.',
    tags: ['steady-flow', 'flow-line-comparison'],
  },
  {
    id: 'flowlines-05', topic: 'flowlines', title: 'Can streamlines cross?',
    kind: 'choice', difficulty: 'Connect',
    prompt: 'Can two streamlines cross with different tangents at a regular point where the instantaneous velocity is nonzero and single-valued?',
    choices: ['Yes, whenever the fluid is incompressible', 'Yes, whenever pressure changes along the flow', 'No: that would require two velocity directions at the same point and instant', 'Yes, if the speed is the same on both lines'], answerIndex: 2,
    hint: 'Each streamline tangent must agree with the local velocity vector.',
    solution: ['A nonzero, single-valued velocity has one direction at the specified point and time.', 'Two different streamline tangents there would contradict that unique direction. The question excludes stagnation points.'],
    takeaway: 'Streamline geometry must be consistent with a single instantaneous velocity field.',
    tags: ['streamlines', 'velocity-direction'],
  },
  {
    id: 'flowlines-06', topic: 'flowlines', title: 'Find a streamline slope',
    kind: 'numeric', difficulty: 'Apply',
    prompt: 'At a point in a two-dimensional flow, the velocity components are u = 4.00 m/s in +x and v = 2.00 m/s in +y. Find the instantaneous streamline slope dy/dx there.',
    given: 'Use Cartesian coordinates. The x-component of velocity is nonzero.',
    answer: 0.5, unit: 'dimensionless', tolerance: 0.005,
    hint: 'The streamline tangent has the same component ratio as the velocity.',
    solution: ['For a streamline, dy/dx = v/u.', 'Here dy/dx = 2.00/4.00 = 0.500.'],
    takeaway: 'A streamline’s local slope is a ratio of velocity components.',
    tags: ['streamlines', 'velocity-components'],
  },
  {
    id: 'continuity-01', topic: 'continuity', title: 'A steady pipe junction',
    kind: 'choice', difficulty: 'Foundation',
    prompt: 'A steady incompressible flow has one inlet and two outlets. Which volumetric-flow relation is correct?',
    given: 'There is no storage or leakage; Qin enters, and Qout,1 and Qout,2 leave the junction.',
    choices: ['Qin = Qout,1 − Qout,2', 'Qin = Qout,1 + Qout,2', 'Qin = Qout,1 = Qout,2 in every junction', 'Qin = (Qout,1 + Qout,2)/2'], answerIndex: 1,
    hint: 'With no accumulation, the total entering mass flow equals the total leaving mass flow.',
    solution: ['Steady conservation of mass gives ρQin = ρQout,1 + ρQout,2.', 'The common density cancels, leaving Qin = Qout,1 + Qout,2.'],
    takeaway: 'At a steady incompressible junction, add all outlet flow rates.',
    tags: ['mass-conservation', 'pipe-junction'],
  },
  {
    id: 'continuity-02', topic: 'continuity', title: 'A contracting pipe',
    kind: 'numeric', difficulty: 'Foundation',
    prompt: 'Steady incompressible flow passes from a 0.100 m diameter pipe into a 0.050 m diameter pipe. If the upstream mean speed is 1.50 m/s, find the downstream mean speed.',
    given: 'Both circular sections are completely filled; there is no leakage.',
    answer: 6, unit: 'm/s', tolerance: 0.01,
    hint: 'Circular area is proportional to diameter squared.',
    solution: ['A1V1 = A2V2, so V2 = V1(D1/D2)².', 'V2 = 1.50 × (0.100/0.050)² = 6.00 m/s.'],
    takeaway: 'A diameter ratio must be squared in a continuity calculation.',
    tags: ['area-velocity', 'pipe-diameter'],
  },
  {
    id: 'continuity-03', topic: 'continuity', title: 'Speed to discharge',
    kind: 'numeric', difficulty: 'Apply',
    prompt: 'A pipe has a flow area of 0.0200 m² and a mean flow speed of 3.00 m/s. Find the volumetric flow rate.',
    given: 'The pipe is completely filled; the stated speed is the area-mean speed.',
    answer: 0.06, unit: 'm³/s', tolerance: 0.0005,
    hint: 'Use Q = A times the area-mean velocity.',
    solution: ['Q = AV = 0.0200 × 3.00 = 0.0600 m³/s.', 'This is also 60.0 L/s, but enter the answer in m³/s.'],
    takeaway: 'Discharge measures volume per unit time, not speed.',
    tags: ['flow-rate', 'units'],
  },
  {
    id: 'continuity-04', topic: 'continuity', title: 'Diameter scaling',
    kind: 'choice', difficulty: 'Apply',
    prompt: 'At fixed volumetric flow rate in a full circular pipe, the diameter is halved. What is the ratio of the new mean speed to the old mean speed?',
    choices: ['0.5', '2', '4', '8'], answerIndex: 2,
    hint: 'Halving the diameter reduces area to one quarter.',
    solution: ['Anew/Aold = (1/2)² = 1/4.', 'Since Q = AV is fixed, Vnew/Vold = Aold/Anew = 4.'],
    takeaway: 'At fixed flow rate, mean speed varies inversely with diameter squared.',
    tags: ['area-velocity', 'scaling'],
  },
  {
    id: 'continuity-05', topic: 'continuity', title: 'Changing density',
    kind: 'numeric', difficulty: 'Connect',
    prompt: 'A steady gas flow enters a duct at ρ1 = 1.20 kg/m³, A1 = 0.0400 m², and V1 = 5.00 m/s. It leaves at ρ2 = 0.800 kg/m³ through A2 = 0.0250 m². Find V2.',
    given: 'One inlet and one outlet, no leakage; density and velocity are uniform across each section.',
    answer: 12, unit: 'm/s', tolerance: 0.02,
    hint: 'Density changes, so conserve ρAV rather than AV.',
    solution: ['Mass flow rate = ρ1A1V1 = 1.20 × 0.0400 × 5.00 = 0.240 kg/s.', 'V2 = 0.240/(0.800 × 0.0250) = 12.00 m/s.'],
    takeaway: 'Steady mass flow is conserved even when volumetric flow changes.',
    tags: ['mass-flow-rate', 'compressible-flow'],
  },
  {
    id: 'continuity-06', topic: 'continuity', title: 'Accumulation in a tank',
    kind: 'choice', difficulty: 'Connect',
    prompt: 'Water enters a tank at 5 L/s and leaves at 3 L/s. What must be included in its mass balance?',
    given: 'Water density is constant; there are no other flows and no overflow.',
    choices: ['An accumulation term: stored water volume increases at 2 L/s', 'No accumulation term, because each flow rate is constant', 'A loss of water mass at 2 L/s', 'Equal inlet and outlet speeds, regardless of area'], answerIndex: 0,
    hint: 'Constant boundary flow rates do not guarantee that the amount inside the control volume is constant.',
    solution: ['The volume balance is dVstored/dt = Qin − Qout.', 'Here dVstored/dt = 5 − 3 = 2 L/s, so the tank contents are accumulating.'],
    takeaway: 'Steadiness must be checked for the control volume, not inferred from constant inlet settings.',
    tags: ['control-volume', 'accumulation'],
  },
  {
    id: 'bernoulli-01', topic: 'bernoulli', title: 'Choose the Bernoulli model',
    kind: 'choice', difficulty: 'Foundation',
    prompt: 'When may p/(ρg) + V²/(2g) + z be taken as constant between two points along one streamline?',
    choices: ['For every flow, including frictional pipe flow through a pump', 'Only when the two points have equal elevation', 'Only when pressure and speed are both constant', 'For steady incompressible flow with negligible viscous loss and no pump or turbine between the points'], answerIndex: 3,
    hint: 'Check the assumptions behind the energy balance before applying its simplified form.',
    solution: ['The simplified Bernoulli relation conserves mechanical energy head along a streamline under the stated ideal-flow assumptions.', 'Losses and shaft-energy transfers require additional terms.'],
    takeaway: 'An equation is useful only when its assumptions fit the chosen flow path.',
    tags: ['energy-conservation', 'model-assumptions'],
  },
  {
    id: 'bernoulli-02', topic: 'bernoulli', title: 'Pressure in a horizontal contraction',
    kind: 'numeric', difficulty: 'Apply',
    prompt: 'Water speeds up from 2.00 m/s to 6.00 m/s in a horizontal pipe. If the upstream gauge pressure is 150.0 kPa, find the downstream gauge pressure.',
    given: 'ρ = 1000 kg/m³. Steady incompressible flow; neglect head loss; no pump or turbine; use uniform section velocities.',
    answer: 134, unit: 'kPa gauge', tolerance: 0.1,
    hint: 'At equal elevation, an increase in kinetic energy comes from a decrease in pressure energy.',
    solution: ['p2 = p1 + ½ρ(V1² − V2²).', 'p2 = 150,000 + ½ × 1000 × (2.00² − 6.00²) = 134,000 Pa.', 'The downstream gauge pressure is 134.0 kPa.'],
    takeaway: 'In this ideal horizontal flow, accelerating the water lowers its pressure.',
    tags: ['pressure-velocity', 'energy-conservation'],
  },
  {
    id: 'bernoulli-03', topic: 'bernoulli', title: 'Discharge from a large tank',
    kind: 'numeric', difficulty: 'Apply',
    prompt: 'An opening is 1.80 m below the water free surface in a large tank. Find the ideal speed of the jet leaving the opening.',
    given: 'g = 9.80 m/s². Free surface and jet are at atmospheric pressure; free-surface speed is negligible. Assume quasi-steady flow and neglect losses.',
    answer: 5.939696961966999, unit: 'm/s', tolerance: 0.02,
    hint: 'Apply Bernoulli from the nearly stationary free surface to the free jet.',
    solution: ['The pressure terms cancel, and the elevation drop becomes velocity head: h = V²/(2g).', 'V = √(2 × 9.80 × 1.80) = 5.940 m/s.'],
    takeaway: 'Ideal tank-outlet speed depends on the vertical head above the outlet.',
    tags: ['tank-discharge', 'elevation-head'],
  },
  {
    id: 'bernoulli-04', topic: 'bernoulli', title: 'An uphill pipe',
    kind: 'choice', difficulty: 'Foundation',
    prompt: 'Steady incompressible flow moves uphill through a full pipe of constant diameter. With no head loss, pump, or turbine, what happens between the lower and higher sections?',
    choices: ['Mean speed increases and pressure stays constant', 'Mean speed stays constant and pressure decreases', 'Mean speed stays constant and pressure increases', 'Both mean speed and pressure must stay constant'], answerIndex: 1,
    hint: 'Use continuity for the speed and Bernoulli for the pressure change.',
    solution: ['Constant area and steady incompressible flow give equal mean speeds.', 'With the velocity terms cancelling, p2 − p1 = −ρg(z2 − z1); pressure falls as elevation rises.'],
    takeaway: 'Elevation can change pressure even when the pipe speed does not change.',
    tags: ['elevation-head', 'continuity-link'],
  },
  {
    id: 'bernoulli-05', topic: 'bernoulli', title: 'The gap between grade lines',
    kind: 'numeric', difficulty: 'Apply',
    prompt: 'At a pipe section where the mean speed is 4.00 m/s, find EGL − HGL.',
    given: 'g = 9.80 m/s²; use kinetic-energy correction factor α = 1. EGL is total energy head and HGL is elevation plus pressure head.',
    answer: 0.8163265306122448, unit: 'm', tolerance: 0.005,
    hint: 'The difference is the local velocity head.',
    solution: ['EGL − HGL = V²/(2g).', 'The gap is 4.00²/(2 × 9.80) = 0.8163 m.'],
    takeaway: 'The vertical separation of the grade lines represents velocity head.',
    tags: ['grade-lines', 'velocity-head'],
  },
  {
    id: 'bernoulli-06', topic: 'bernoulli', title: 'Account for a head loss',
    kind: 'choice', difficulty: 'Connect',
    prompt: 'A steady pipe flow has a positive head loss between an upstream and downstream section, with no pump or turbine. How does downstream total energy head compare with upstream total energy head?',
    choices: ['It is larger by the head loss', 'It is unchanged because mass is conserved', 'It is smaller by the head loss', 'It must be zero at the downstream section'], answerIndex: 2,
    hint: 'Write the energy equation with the loss term on the downstream side.',
    solution: ['The mechanical-energy balance is Hupstream = Hdownstream + hL.', 'Since hL > 0, Hdownstream = Hupstream − hL. The energy grade line drops.'],
    takeaway: 'Mass conservation does not imply conservation of mechanical energy when losses occur.',
    tags: ['head-loss', 'energy-conservation'],
  },
  {
    id: 'momentum-01', topic: 'momentum', title: 'Choose the momentum balance',
    kind: 'choice', difficulty: 'Foundation',
    prompt: 'For a stationary control volume with steady flow, one inlet, one outlet, and uniform section velocities, which vector equation gives the net external force on the fluid?',
    given: 'The mass flow rate ṁ is the same at inlet and outlet. Include pressure, wall, and body forces in the force sum.',
    choices: ['ΣF = ṁ(Vout − Vin)', 'ΣF = ṁ(Vout + Vin) for every geometry', 'ΣF = ρg times the control-volume surface area', 'ΣF = 0 whenever the flow is steady'], answerIndex: 0,
    hint: 'Steady flow removes momentum accumulation, not the momentum carried across the boundary.',
    solution: ['Net external force equals momentum outflow rate minus momentum inflow rate.', 'Thus ΣF = ṁVout − ṁVin = ṁ(Vout − Vin), with vector velocities.'],
    takeaway: 'A steady flow can exert a force by changing its momentum flux.',
    tags: ['control-volume', 'momentum-flux'],
  },
  {
    id: 'momentum-02', topic: 'momentum', title: 'A water jet strikes a plate',
    kind: 'numeric', difficulty: 'Apply',
    prompt: 'A horizontal water jet strikes a stationary flat plate normally. Find the force exerted by the water on the plate in the incoming jet direction.',
    given: 'ρ = 1000 kg/m³; jet area = 0.00200 m²; speed = 10.0 m/s. The full jet is intercepted and leaves sideways with zero velocity component in the incoming direction. Free-jet boundaries are at atmospheric pressure; neglect gravity in this direction.',
    answer: 200, unit: 'N', tolerance: 0.5,
    hint: 'First find the mass flow rate. The plate removes the incoming component of the fluid momentum.',
    solution: ['Q = AV = 0.00200 × 10.0 = 0.0200 m³/s; ṁ = ρQ = 20.0 kg/s.', 'The plate force on the water is ṁ(0 − 10.0) = −200 N.', 'The water exerts the opposite force on the plate: +200 N in the incoming jet direction.'],
    takeaway: 'State whether a momentum result is the force on the fluid or the reaction on the solid.',
    tags: ['jet-force', 'action-reaction'],
  },
  {
    id: 'momentum-03', topic: 'momentum', title: 'Turning a free jet through 90 degrees',
    kind: 'numeric', difficulty: 'Apply',
    prompt: 'A stationary vane turns a water jet from +x into +y without changing its speed. Find the x-component of the force exerted by the vane on the water; include its sign.',
    given: 'ρ = 1000 kg/m³; Q = 0.0100 m³/s; inlet and outlet speeds = 8.00 m/s. Both free-jet sections are at atmospheric pressure; neglect gravity and other external forces.',
    answer: -80, unit: 'N', tolerance: 0.2,
    hint: 'The outlet has zero x-velocity. This question asks for the force on the water.',
    solution: ['ṁ = 1000 × 0.0100 = 10.0 kg/s.', 'Fx,on water = ṁ(Vout,x − Vin,x) = 10.0 × (0 − 8.00) = −80.0 N.'],
    takeaway: 'Apply momentum separately to each coordinate and keep the velocity signs.',
    tags: ['jet-turning', 'vector-momentum'],
  },
  {
    id: 'momentum-04', topic: 'momentum', title: 'Direction of the vane reaction',
    kind: 'choice', difficulty: 'Connect',
    prompt: 'A stationary vane turns a free jet from +x into +y at unchanged speed. In which directions are the force components exerted by the water on the vane?',
    given: 'The full jet is turned; inlet and outlet are at atmospheric pressure. Neglect gravity and other external forces.',
    choices: ['−x and +y', '+x and +y', '−x and −y', '+x and −y'], answerIndex: 3,
    hint: 'Find the vane’s force on the fluid from the change in momentum, then reverse it.',
    solution: ['The fluid loses +x momentum and gains +y momentum, so the vane’s force on it points −x and +y.', 'By Newton’s third law, the water’s force on the vane points +x and −y.'],
    takeaway: 'The solid reaction is opposite to the force producing the fluid’s momentum change.',
    tags: ['vector-momentum', 'action-reaction'],
  },
  {
    id: 'momentum-05', topic: 'momentum', title: 'Reverse a jet',
    kind: 'numeric', difficulty: 'Apply',
    prompt: 'A stationary smooth vane reverses a water jet from +x to −x at unchanged speed. Find the magnitude of the force exerted by the water on the vane.',
    given: 'ρ = 1000 kg/m³; Q = 0.0200 m³/s; speed = 5.00 m/s. The full jet is reversed; both free-jet sections are at atmospheric pressure; neglect gravity and other forces.',
    answer: 200, unit: 'N', tolerance: 0.5,
    hint: 'A reversed velocity is negative. Its change is not zero just because the speed is unchanged.',
    solution: ['ṁ = 1000 × 0.0200 = 20.0 kg/s.', 'Force on water = 20.0 × (−5.00 − 5.00) = −200 N.', 'The force on the vane is +200 N, so its magnitude is 200 N.'],
    takeaway: 'Reversing a jet doubles the change in its incoming-direction velocity component.',
    tags: ['jet-turning', 'momentum-flux'],
  },
  {
    id: 'momentum-06', topic: 'momentum', title: 'Pressure force at an inlet',
    kind: 'choice', difficulty: 'Foundation',
    prompt: 'Water enters a stationary control volume through its left face and flows in +x. If the inlet gauge pressure is positive, in which direction does the inlet pressure force act on the fluid inside the control volume?',
    choices: ['In −x, because this is an inlet', 'In +x, into the control volume', 'It is zero whenever the flow is steady', 'It acts tangentially to the inlet face'], answerIndex: 1,
    hint: 'Pressure pushes inward on a control-volume face: the force is opposite to the outward normal.',
    solution: ['The outward unit normal of the left inlet face is −x.', 'Pressure force is −pAn, so positive inlet gauge pressure produces a +x contribution.'],
    takeaway: 'Use the control-volume face normal to determine pressure-force signs.',
    tags: ['pressure-force', 'control-volume'],
  },
  {
    id: 'mixed-01', topic: 'mixed', relatedTopics: ['pressure', 'forces'], title: 'From pressure distribution to gate load',
    kind: 'numeric', difficulty: 'Connect',
    prompt: 'A vertical rectangular gate is 1.00 m wide and extends from 1.00 m to 3.00 m below an open water surface. Find its net hydrostatic force magnitude.',
    given: 'ρ = 1000 kg/m³; g = 9.80 m/s²; water at rest on one side and atmospheric pressure on the other.',
    answer: 39.2, unit: 'kN', tolerance: 0.1,
    hint: 'Find the average gauge pressure over the gate, then multiply by its area.',
    solution: ['Top and bottom gauge pressures are 9.80 kPa and 29.40 kPa.', 'The linear distribution has average pressure (9.80 + 29.40)/2 = 19.60 kPa.', 'Gate area = 1.00 × (3.00 − 1.00) = 2.00 m²; F = 19.60 × 2.00 = 39.20 kN.'],
    takeaway: 'Hydrostatic force is the area integral of the pressure distribution.',
    tags: ['pressure-to-force', 'plane-surface'],
  },
  {
    id: 'mixed-02', topic: 'mixed', relatedTopics: ['continuity', 'bernoulli'], title: 'A pipe reducer with two balances',
    kind: 'numeric', difficulty: 'Connect',
    prompt: 'A horizontal water pipe contracts from diameter 0.100 m to 0.050 m. Upstream speed is 1.00 m/s and gauge pressure is 100.0 kPa. Find the downstream gauge pressure.',
    given: 'ρ = 1000 kg/m³; steady incompressible flow with uniform section velocities; no leakage, head loss, pump, or turbine.',
    answer: 92.5, unit: 'kPa gauge', tolerance: 0.05,
    hint: 'Use continuity to find the downstream speed before applying Bernoulli.',
    solution: ['V2 = 1.00 × (0.100/0.050)² = 4.00 m/s.', 'p2 = 100,000 + ½ × 1000 × (1.00² − 4.00²) = 92,500 Pa.', 'The downstream gauge pressure is 92.50 kPa.'],
    takeaway: 'Continuity and energy conservation answer different parts of the same flow problem.',
    tags: ['continuity-and-energy', 'pipe-reducer'],
  },
  {
    id: 'mixed-03', topic: 'mixed', relatedTopics: ['bernoulli', 'continuity', 'momentum'], title: 'Tank head to jet force',
    kind: 'numeric', difficulty: 'Connect',
    prompt: 'A large water tank produces a horizontal jet that strikes a stationary plate normally at the outlet elevation. Find the force exerted by the water on the plate in the jet direction.',
    given: 'Free surface is 5.00 m above the outlet; jet area at the plate = 0.00100 m²; ρ = 1000 kg/m³; g = 9.80 m/s². Assume quasi-steady lossless discharge, negligible free-surface speed, and atmospheric pressure at the free surface and jet. The full jet is intercepted and leaves sideways with zero incoming-direction velocity component.',
    answer: 98, unit: 'N', tolerance: 0.3,
    hint: 'Use tank head to obtain V², then combine Q = AV with the plate momentum balance.',
    solution: ['Bernoulli gives V² = 2gh = 2 × 9.80 × 5.00 = 98.0 m²/s².', 'For full normal interception, force on the plate is ρQV = ρAV².', 'F = 1000 × 0.00100 × 98.0 = 98.0 N in the incoming jet direction.'],
    takeaway: 'Energy determines jet speed; momentum determines the force it produces.',
    tags: ['energy-to-momentum', 'jet-force'],
  },
  {
    id: 'mixed-04', topic: 'mixed', relatedTopics: ['flowlines', 'continuity', 'momentum'], title: 'Use a stream surface as a boundary',
    kind: 'choice', difficulty: 'Connect',
    prompt: 'In a steady flow, part of a stationary control-volume boundary is chosen to be a stream surface. Which statement is correct for that part of the boundary?',
    choices: ['There is no normal mass flux, but pressure forces may still act', 'There is no pressure force because no fluid crosses it', 'The fluid velocity must be zero everywhere on it', 'Mass may cross it freely because the control volume is imaginary'], answerIndex: 0,
    hint: 'Velocity is tangent to a stream surface, whereas pressure acts normal to a surface.',
    solution: ['The normal velocity is zero on the stream surface, so ρV·n gives zero mass flux there.', 'Zero mass flux does not remove the pressure term from a momentum balance.'],
    takeaway: 'A convenient flow boundary can simplify flux terms without eliminating forces.',
    tags: ['stream-surface', 'control-volume'],
  },
  {
    id: 'mixed-05', topic: 'mixed', relatedTopics: ['continuity', 'bernoulli', 'momentum'], title: 'Plan an elbow-force calculation',
    kind: 'choice', difficulty: 'Connect',
    prompt: 'You know the flow rate through a steady pipe elbow and need the force the fluid exerts on the elbow. Which calculation plan is appropriate?',
    given: 'The section areas, elevations, and at least one section pressure are known; any use of Bernoulli must satisfy its assumptions or include the required energy terms.',
    choices: ['Use Bernoulli alone: it directly gives a force vector', 'Use continuity alone: equal mass flows imply zero elbow force', 'Find velocities from continuity, obtain needed pressures from an appropriate energy relation, then apply vector momentum and reverse the wall-on-fluid force', 'Find the fluid weight and ignore pressure and momentum fluxes'], answerIndex: 2,
    hint: 'Separate mass, energy, and momentum balances, and identify whose force is requested.',
    solution: ['Continuity relates the section velocities to the flow rate.', 'An appropriate energy equation can supply unknown section pressures.', 'Vector momentum includes pressure, wall, and relevant body forces. The fluid-on-elbow force is opposite to the elbow-on-fluid force.'],
    takeaway: 'A force calculation often needs several balances, with each playing a distinct role.',
    tags: ['balance-selection', 'elbow-force'],
  },
  {
    id: 'mixed-06', topic: 'mixed', relatedTopics: ['pressure', 'forces', 'momentum'], title: 'Forces without flow',
    kind: 'choice', difficulty: 'Connect',
    prompt: 'Water is at rest in a stationary tank. What does zero momentum flux imply about the forces on the water?',
    given: 'The water is in static equilibrium under gravity.',
    choices: ['Every pressure force is zero', 'The water has no weight', 'Only horizontal pressure forces can exist', 'The net external force is zero, while individual pressure forces and weight can be nonzero'], answerIndex: 3,
    hint: 'A zero force sum is different from every force being zero.',
    solution: ['Static equilibrium has neither momentum accumulation nor momentum flux.', 'The vector sum of pressure forces, any other boundary forces, and water weight is zero; the individual contributions can remain nonzero.'],
    takeaway: 'Hydrostatics is consistent with the zero-motion limit of the momentum balance.',
    tags: ['static-equilibrium', 'balance-selection'],
  },
];
